import type { Product } from '@/types'

// Used as fallback when Supabase is unavailable or during development.
// rating and review_count are intentionally null/0 — real values come from the DB only.
export const PRODUCTS = [
  {
    id: '1',
    slug: 'bakuchiol-renewal-serum',
    image_url: '/images/products/serum.webp',
    name: 'Bakuchiol Renewal Serum',
    category: 'Serum',
    price: 250,
    rating: null,
    review_count: 0,
    skin_types: ['Dry', 'Combination'],
    badges: ['Vegan', 'Organic Certified'],
    description: 'Plant-based retinol alternative for visible cell renewal without irritation.',
    ingredient: 'Bakuchiol',
    bg_color: '#EBF0E9',
    emoji: '🌿',
  },
  {
    id: '2',
    slug: 'rose-hip-glow-moisturiser',
    image_url: '/images/products/moisturiser.webp',
    name: 'Rose Hip Glow Moisturiser',
    category: 'Moisturiser',
    price: 390,
    rating: null,
    review_count: 0,
    skin_types: ['Dry', 'Sensitive'],
    badges: ['Cruelty-Free', 'Vegan'],
    description: 'Rich cloud-like hydration with rosehip oil and ceramides for lasting softness.',
    ingredient: 'Rose Hip',
    bg_color: '#F6EDE8',
    emoji: '🌹',
  },
  {
    id: '3',
    slug: 'green-tea-clarity-toner',
    image_url: '/images/products/toner.webp',
    name: 'Green Tea Clarity Toner',
    category: 'Toner',
    price: 450,
    rating: null,
    review_count: 0,
    skin_types: ['Oily', 'Combination'],
    badges: ['Vegan', 'Organic Certified'],
    description: 'Balance oil and refine pores with antioxidant-rich green tea extract.',
    ingredient: 'Green Tea',
    bg_color: '#E8F2EA',
    emoji: '🍃',
  },
  {
    id: '4',
    slug: 'turmeric-brightening-cleanser',
    image_url: '/images/products/cleanser.webp',
    name: 'Turmeric Brightening Cleanser',
    category: 'Cleanser',
    price: 250,
    rating: null,
    review_count: 0,
    skin_types: ['All Types'],
    badges: ['Cruelty-Free', 'Organic Certified'],
    description: 'Gentle foam cleanser with turmeric and neem for a luminous complexion.',
    ingredient: 'Turmeric',
    bg_color: '#F5F0E4',
    emoji: '✨',
  },
  {
    id: '5',
    slug: 'botanical-spf-50-shield',
    image_url: '/images/products/spf.webp',
    name: 'Botanical SPF 50 Shield',
    category: 'SPF',
    price: 220,
    rating: null,
    review_count: 0,
    skin_types: ['All Types'],
    badges: ['Vegan', 'Cruelty-Free'],
    description: 'Featherlight mineral sunscreen with zinc oxide and soothing aloe vera.',
    ingredient: 'Zinc Oxide',
    bg_color: '#FFF8E8',
    emoji: '☀️',
  },
  {
    id: '6',
    slug: 'wild-berry-lip-elixir',
    image_url: '/images/products/lip-elixir.webp',
    name: 'Wild Berry Lip Elixir',
    category: 'Lip Care',
    price: 490,
    rating: null,
    review_count: 0,
    skin_types: ['All Types'],
    badges: ['Vegan', 'Organic Certified'],
    description: 'Nourishing lip treatment with acai berry and shea for pillowy softness.',
    ingredient: 'Acai Berry',
    bg_color: '#F0E8F5',
    emoji: '🫐',
  },
  {
    id: '7',
    slug: 'niacinamide-pore-serum',
    image_url: '/images/products/niacinamide-serum.webp',
    name: 'Niacinamide Pore Serum',
    category: 'Serum',
    price: 350,
    rating: null,
    review_count: 0,
    skin_types: ['Oily', 'Combination'],
    badges: ['Vegan', 'Cruelty-Free'],
    description: 'Minimise pores and control sebum with a 10% niacinamide complex.',
    ingredient: 'Niacinamide',
    bg_color: '#E8EFF5',
    emoji: '💧',
  },
  {
    id: '8',
    slug: 'shea-butter-night-cream',
    image_url: '/images/products/night-cream.webp',
    name: 'Shea Butter Night Cream',
    category: 'Moisturiser',
    price: 550,
    rating: null,
    review_count: 0,
    skin_types: ['Dry', 'Sensitive'],
    badges: ['Organic Certified', 'Cruelty-Free'],
    description: 'Intensive overnight repair with shea butter and vitamin E for morning glow.',
    ingredient: 'Shea Butter',
    bg_color: '#F5EBF0',
    emoji: '🌙',
  },
] satisfies Product[]

export const CATEGORIES = [
  'All',
  'Serum',
  'Moisturiser',
  'Toner',
  'Cleanser',
  'SPF',
  'Lip Care',
] as const
export const SKIN_TYPES = ['All', 'Dry', 'Oily', 'Combination', 'Sensitive'] as const
export const SORT_OPTIONS = [
  'Bestselling',
  'Price Low→High',
  'Price High→Low',
  'Top Rated',
] as const

export interface LoyaltyTier {
  name: string
  min: number
  max: number
  color: string
  emoji: string
}

export const TIERS: LoyaltyTier[] = [
  { name: 'Green Leaf', min: 0, max: 499, color: '#3D6344', emoji: '🌿' },
  { name: 'Gold Botanist', min: 500, max: 1499, color: '#BFA06A', emoji: '🏆' },
  { name: 'Platinum Alchemist', min: 1500, max: Infinity, color: '#7B8FA6', emoji: '💎' },
]
